
#this is optional, to describe the meta metrics, like: you have go_goroutines and go_threads, you can set the MetricMeta as GoInformation
MetricMeta="Go_Information"

Url="http://localhost:8088/metrics"

FreshDura=3

GetDura=3

Persist=true

PersistDura=3

MetricsShowing=["go_memstats_alloc_bytes","go_memstats_frees_total","go_memstats_mspan_inuse_bytes","go_threads","go_goroutines","go_memstats_heap_idle_bytes"]

[DB]
Url = "http://localhost:8086"
Enabled = true
User = ""
Password = ""
